### ISSUE TITLE
Disallow uploading own identity

### ISSUE THREAD

**Issue by PeterNerlich** [Max-F-Helm/Signage#3]
In the *Create Proposal* sections of the *Open or Create Document* dialog, uploading the own identity is allowed. The file name shows up in the authors list, but the dialog displays *there was an error while creating the proposal (author-file identity.sIdn is corrupted)*.

Ideally, the application should check whether the file is a distinct author or not and display a message accordingly. (*file corrupted* is not a user friendly message when created by user action through the application)

**Comment by PeterNerlich** [comment]
The error logged to console when displaying the message is the same as in #4, the issues might be related.

**Comment by Max-F-Helm** [comment]
it looks like you uploaded the identity-file; you have to use author-files (*.sAut).

**Comment by Max-F-Helm** [comment]
It is difficult to check the author if an author-file without uploading it at selection (which could lead to problematic timing conditions).
I will try to make a new error-message if the own author was uploaded or selected.
